
services:
  db:
    image: postgres:16
    container_name: financeflow_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata_v2:/var/lib/postgresql/data
      - ./backend/initdb:/docker-entrypoint-initdb.d   # scripts de inicialização
    ports:
      - "5432:5432"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: financeflow_api
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - db
    ports:
      - "8000:8000"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: financeflow_web
    restart: always
    env_file:
      - .env
    depends_on:
      - api
    ports:
      - "80:80"

volumes:
  pgdata_v2:
