services:
  db:
    image: postgres:16-alpine
    container_name: financeflow_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - financeflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    container_name: financeflow_api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
    networks:
      - financeflow
    ports:
      - "8000:8000"

  web:
    build: ./frontend
    container_name: financeflow_web
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "8080:80"
    networks:
      - financeflow

volumes:
  db_data:

networks:
  financeflow:
    driver: bridge

