

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks: [financeflow]

  api:
    build: ./backend
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on: [db]
   
    networks: [financeflow]

  web:
    build: ./frontend
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://api:8000
    depends_on: [api]
    ports:
      - "5173:80"
    networks: [financeflow]

volumes:
  db_data:

networks:
  financeflow:
    driver: bridge
